# https://taskfile.dev

version: "3"

tasks:
  update-chat-files:
    desc: Update chat files
    cmds:
      - ./scripts/import_all_streams.sh

  db:reset:
    desc: Reset the database
    cmds:
      - node ace migration:fresh

  db:seed:
    desc: Reset the database
    deps: [db:reset]
    cmds:
      - node ace db:seed -f database/seeders/user_seeder.ts
      - node ace db:seed -f database/seeders/message_seeder.ts
