name: emdpr

services:
  server:
    container_name: emdpr-server
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    depends_on:
      - postgres
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - 43000:3000
    command: >
      bash -c "node ace migration:run --force && node ./bin/server.js"

  postgres:
    container_name: emdpr-postgres
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env.production
    volumes:
      - emdpr-postgres:/var/lib/postgresql/data

volumes:
  emdpr-postgres:
